array1=('ModelNet40' 'NTU2012' 'Mushroom' 'coauthor_cora' 'yelp' 'house-committees' 'cora' 'citeseer' 'pubmed' 'actor' 'pokec' 'twitch' '20newsW100' 'walmart-trips' 'coauthor_dblp')
# Only for house (learnmask)=>    python train_sparse.py --method CEGAT --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode learnmask --reg none
# Only for house (full) => python train_sparse.py --method CEGAT --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 8 --Classifier_num_layers 1 --MLP_hidden 128 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode full --reg none

for dataset in "${array1[@]}"; do
    python train_sparse.py --method CEGAT --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0 --seed 1 --mode learnmask --reg none
    python train_sparse.py --method CEGCN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0 --seed 1 --mode learnmask --reg none
    python train_sparse.py --method AllSetTransformer --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0 --seed 5 --mode learnmask --reg none   
    python train_sparse.py --method CEGAT --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0 --seed 1 --mode full --reg none
    python train_sparse.py --method CEGCN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 64 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0 --seed 1 --mode full --reg none
    python train_sparse.py --method AllSetTransformer --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 4 --Classifier_num_layers 1 --MLP_hidden 256 --Classifier_hidden 128 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.001 --perturb_type replace --perturb_prop 0 --seed 5 --mode full --reg none
done 