array1=('ModelNet40' 'NTU2012' 'Mushroom' 'coauthor_cora' 'yelp' 'house-committees' 'cora' 'citeseer' 'pubmed' 'actor' 'pokec' 'twitch' '20newsW100' 'walmart-trips' 'coauthor_dblp')
for dataset in "${array1[@]}"; do
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode learnmask # EHGNN-F
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode learnmask_cond # EHGNN-F + cond.
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode random
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode degdist 
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode effresist
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode full 
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode learnmask+ # EHGNN-C + cond
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode learnmask+_agn # EHGNN-C
    python train_sparse.py --method HGNN --dname $dataset --All_num_layers 1 --MLP_num_layers 2 --feature_noise 0.0 --heads 1 --Classifier_num_layers 1 --MLP_hidden 512 --Classifier_hidden 256 --wd 0.0 --epochs 500 --runs 5 --cuda 0 --lr 0.0005 --perturb_type replace --perturb_prop 0 --seed 1 --mode Neural
done 
